# Generated by Django 4.1.2 on 2022-11-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_liketoarticle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comm',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
