# Generated by Django 4.1.2 on 2022-11-06 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_date_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
